pterodactyl/panel

app/Http/Controllers/Auth/PasswordController.php
app/Http/Routes/AuthRoutes.php
resources/lang/en/auth.php
resources/lang/en/strings.php
resources/views/auth/password.blade.php
resources/views/auth/reset.blade.php
resources/views/emails/password.blade.php

Migrates the ability to reset passwords. We are using the built-in Laravel Authentication system to handle this. This has been manually tested.
Please see [http://board.pterodactyl.co/b/XcujphkBduZAWcXL9/pufferpanel-0-9-0/3c7DP7q2TwMi2pobA](http://board.pterodactyl.co/b/XcujphkBduZAWcXL9/pufferpanel-0-9-0/3c7DP7q2TwMi2pobA) for more details.

Migrate ability to reset passwords

---

resources/views/auth/login.blade.php

This PR fixes a bug when Two-Factor authentication is not enabled, the AJAX "rapid fires" and does not submit the form and log the user in as expected.

Fix TOTP AJAX

---

app/Http/Controllers/Admin/AccountsController.php
app/Http/Controllers/Base/IndexController.php
app/Http/Routes/AdminRoutes.php
app/Http/Routes/BaseRoutes.php
resources/views/admin/accounts/new.blade.php

This allows accounts to be created in the Admin Control Panel. It was tested manually.
@DaneEveritt remember to add in UUID checking when you get a chance.

Account Creation in AdminCP

---

app/Http/Controllers/Admin/AccountsController.php
app/Http/Routes/AdminRoutes.php
app/Repositories/UserRepository.php
resources/lang/en/base.php
resources/lang/en/server.php
resources/lang/en/strings.php
resources/views/admin/accounts/view.blade.php
resources/views/emails/new_password.blade.php

This pull requests implements an interface into the Admin Panel that allows
users to be viewed, modified, and deleted.

View and Delete Users

---

app/Http/Controllers/Server/ServerController.php
app/Models/User.php
app/Notifications/AccountCreated.php
app/Repositories/UserRepository.php
app/Services/UuidService.php
composer.json
config/queue.php
database/migrations/2016_09_04_182835_create_notifications_table.php
resources/views/vendor/notifications/email-plain.blade.php
resources/views/vendor/notifications/email.blade.php

Adds initial support for notifications throughout the panel.
This specific PR simply adds one for account creation and fixes a UUID bug that was breaking queues.

Implement base notifications support

---

app/Repositories/UserRepository.php

This PR fixes #106.
Basically, this fix just throws a `DisplayException`, if the currently authenticated user's ID, matches the ID of the user being viewed.

Make sure that you can't delete your own account.

---

resources/views/admin/nodes/index.blade.php

When having multiple nodes, the status was only set for one node

Fix node view in admin panel

---

app/Http/Controllers/API/LocationController.php
app/Http/Controllers/API/NodeController.php
app/Http/Controllers/API/ServerController.php
app/Http/Controllers/API/ServiceController.php
app/Http/Controllers/API/User/InfoController.php
app/Http/Controllers/API/User/ServerController.php
app/Http/Controllers/API/UserController.php
app/Http/Controllers/Base/APIController.php
app/Http/Routes/APIRoutes.php
app/Http/Routes/BaseRoutes.php
app/Models/ServiceOptions.php
app/Models/Subuser.php
app/Policies/ServerPolicy.php
app/Repositories/APIRepository.php
app/Repositories/Daemon/FileRepository.php
app/Repositories/ServerRepository.php
app/Repositories/ServiceRepository/Option.php
app/Repositories/ServiceRepository/Service.php
app/Repositories/ServiceRepository/Variable.php
app/Repositories/UserRepository.php
resources/views/admin/databases/index.blade.php

As discussed in the discord, here is a PR refactoring a few bits and pieces to streamline a few methods (mostly the API) with the help of the integrated laravel helper methods and classes.
While going through the code on my PHP 5.6 development machine, I noticed a few issues regarding the usage of reserved keywords as method names. Those should be fixed, so servers without fancy PHP 7 can now run the panel just fine.

Refactor to use more laravel logic and improve compatibility with older PHP versions

---

app/Console/Commands/MakeUser.php
app/Models/User.php
app/Repositories/UserRepository.php

Repair functionality of the make user console command (pterodactyl:user)
Fix up the user repository, was using the old $password instead of the changed format $data['password']
Change User model to allow root_admin to be a fillable item.

Repair user creation functionality

---

CHANGELOG.md
resources/themes/pterodactyl/base/index.blade.php

Another solution to this would be to change it in the javascript - I wasn't sure which you prefered so i just removed the class for dynamic update so it doesn't call the ajax status (which is hidden behind the checkServer middleware)

show Suspended server in overview fixes #386

---

config/app.php
resources/lang/en/server.php

The drop down menu option was previously "Send Power Toggle" where the help text below it was referring to it as "Send Power Option"
This could probably be changed either way, however I think "option" makes more sense than toggle.

Set drop-down menu option to be same as help text below

---

database/migrations/2017_04_20_171943_AddScriptsToServiceOptions.php

Currently mysql does not support defaults for text and blobs without disabling strict mode in 5.7. https://dev.mysql.com/doc/refman/5.7/en/blob.html
Mariadb (a drop in replacement for mysql made by the same team of devs as mysql) also doesnt support defaults for text and blobs until 10.2.1 (there is no stable release, 10.2.5 is a release candidate) which isnt available on non-bleeding edge distro's. No one is going to install an unstable release of mariadb on production servers. https://mariadb.com/kb/en/mariadb/text/
Latest release for ubuntu xenial is 10.0.29-MariaDB
So for now we change text to string for values that have defaults until defaults are more widely supported for TEXT and BLOB mysql values.

TEXT/BLOB defaults not widely supported. Use STRING/VARCHAR instead.

---

public/themes/pterodactyl/js/frontend/console.js

The original statement seems to be a bit too precise regarding the height. Any tiny lag or one pixel movement leads to the console not being scrolled to the bottom anymore. Same applies for manually scrolling down which does not hide the `terminalNotify` properly. 
A bit larger "buffer" fixes this.

Fix terminal scrolling and terminalNotify

---

app/Http/Controllers/Admin/NodesController.php
resources/themes/pterodactyl/admin/nodes/new.blade.php

The node creation page now displays the old values upon failing to properly create a node. The second commit changes the redirect to the node allocations page as described in issue #535.

Fix node creation page not displaying old values and change redirect after creation

---

resources/themes/pterodactyl/layouts/admin.blade.php
resources/themes/pterodactyl/layouts/master.blade.php

Use universal sign out icons because power buttons are already used in the themes\pterodactyl\admin\nodes\view\settings.blade.php

Use universal sign out icons because power buttons are already used

---

resources/lang/en/navigation.php
resources/themes/pterodactyl/layouts/master.blade.php

This adds a link to the admin page of the current server to the navigation on the left.
It's currently labeled "Manage".
This is untested but should work (The daemon let me down)
resolves #696

add link on server navigation to get to the admin page

---

public/themes/pterodactyl/js/frontend/console.js

think it's obvious what the problem was :)
problem 1 on #706

Fix for js console causing browser to become unresponsive

---

database/seeds/eggs/rust/egg-rust.json

Since laravel only takes 1, 0, true, false, "1", and "0" instead of allowing "true" and "false", it fails to validate with the default value.

Workaround for improper boolean handling

---

public/themes/pterodactyl/css/pterodactyl.css

Before: 
After: 
Non-cascaded: https://user-images.githubusercontent.com/1296882/34921027-5b9e41c4-f94a-11e7-8c04-c0832f1dcd4c.png

Fix #872 - Logo cutoff when cascaded

---

README.md

They are nowhere to be found on latest dev branch, correct me if they should still be there.

Remove mentions of 404/403 .jpg files

---

Vagrantfile

Now using a Vagrant guidelines compliant image, not the official one from ubuntu (they use a user called "ubuntu" instead of "vagrant" for example)
Also now using a .test top level domain for the vagrant dns plugin as Google bought the .app domain and are enforcing HTTPS on it (annoying for development). The .test TLD is protected for testing and development.

Improve the Vagrantfile a little

---

database/seeds/eggs/minecraft/egg-forge-minecraft.json

The GET_VERSIONS Grep Command will fail with 1.12.2 but will work with 1.12. Added optional check for 3rd decimal place in the MC Version of Forge and future proofed the forge version for Double Numeric SubMinor version.

Allow for 3 decimals MC Ver, future proof Forge Install

---

public/themes/pterodactyl/js/frontend/files/upload.js

The reason that this is a warning is because it's technically impossible to tell if the dragged item is a file or a folder: https://stackoverflow.com/questions/25016442/how-to-distinguish-if-a-file-or-folder-is-being-dragged-prior-to-it-being-droppe
The best bet is to check for a size of 0 and no extension. However this would still allow people to drop empty extensionless files if wanted.
[[meta] Chrome History, I have now mastered Drag + Dropz](https://user-images.githubusercontent.com/1296882/40645151-7f568c94-62f3-11e8-81ef-daacc71f4484.png)

Warn users about uploading folders not working and resolve #599

---

resources/themes/pterodactyl/admin/nodes/view/servers.blade.php
resources/themes/pterodactyl/base/index.blade.php
resources/themes/pterodactyl/server/databases/index.blade.php

This should fix a problem occuring in
`Chrome 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)`
Difference: Using the unicode symbol and the HTML symbol

Use appropiate infinity signs

---

app/Providers/SettingsServiceProvider.php

Right now, we drop the exception encountered during boot() of the SettingsServiceProvider. This leads to a mostly unhelpful message. I have added `$exception->getMessage()` to the message logged to the Laravel logs.

Simple query exception logging

---

database/seeds/eggs/voice-servers/egg-teamspeak3-server.json

New minimal Script based on bash.
ts3server.ini is not needed, because its only used when the server get started with the inifile=ts3server.ini parameter.
Also the license aggrement moved to the parameter.

Updated TS3 Server egg

---

database/seeds/eggs/minecraft/egg-spigot.json

Older versions of spigot used "bash" during the install,  added `bash` package

Fixed building of older versions

---

CHANGELOG.md
resources/themes/pterodactyl/server/files/list.blade.php

Due to missing URL encoding, files could not be edited in some cases where the file path contains URL characters with special meaning.  
For more details, please view the issue.
Fixes: #1450

Fix an edge case where files could not be edited from the file manager

---

resources/themes/pterodactyl/partials/admin/settings/notice.blade.php

Updates notice to reflect the correct name of the value to edit, less confusion
As its called `APP_ENVIROMENT_ONLY` and not `LOAD_ENVIROMENT_ONLY`
https://github.com/pterodactyl/panel/blob/develop/config/pterodactyl.php#L14

Update load environment only notice

---

app/Http/Controllers/Admin/ServersController.php
app/Http/Controllers/Server/DatabaseController.php
app/Services/Databases/DatabaseManagementService.php

When creating a new database the password length is 16, but when performing a password reset, the new password is created with a length of 20 characters. While I'm not sure if this was done on purpose, this PR matches the 16 character length on password resets for consistency.
---
This is a duplicate of #1387

Match original database password length when doing a password reset

---

public/themes/pterodactyl/js/frontend/console.js

Neither the cpu chart nor the memory chart use a minimum/maximum for the yAxes values.  
This results in the memory chart having +/-2MB of the servers memory and the cpu chart having negative values.

Change Console Chart yAxes to start at 0 and calculate maximum depending on server config

---

resources/themes/pterodactyl/admin/settings/mail.blade.php

Proposing this change to the mail view to reference the parent section for footer scripts to add the AdminLTE scripts to fix the fact that on smaller resolutions/mobile devices when you need to scroll you can't.
Issue #1591

Proposed changes to fix #1591 (No Scrolling on Mail Settings)

---

resources/themes/pterodactyl/admin/nodes/view/settings.blade.php

I found that when checking just the `public` field, false is not returning `0` unless you cast it to an integer. Casting will not work properly for the way it's setup (I tried a few different combinations, just in case someone suggested it). I tested and noticed conditionals still work as expected (obviously) but since we do a strict comparison with a string, it will also result in the first item being checked.
I just changed it to a normal conditional, however...it may not work with the return of the `old` input. So we could add an or condition or remove the strict conditional checking and it could work as well, but not sure if that's the route you'd like to take. I'll update my commits accordingly depending on the decision.
Reference Issue #1549

Fix the wrong field being ticket for allocation input on node settings (#1549)

---

tests/Unit/Services/Databases/DatabasePasswordServiceTest.php

Failed asserting that [aIIXVo8WqAQ4uhvN.!uZtMeQ] contains 2 to 6 special characters.
Test:
```
<?php
$pattern = preg_quote(' !"#$%&\'()*+,-./:;<=>?@[\]^_`/{}|\|~', '#');
preg_match_all("#[{$pattern}]#", "aIIXVo8WqAQ4uhvN.!uZtMeQ", $matches, PREG_SET_ORDER);
var_dump(count($matches));
var_dump(count($matches) >= 2 && count($matches) <= 6);
preg_match_all("#[{$pattern}]#", 'he||o wor|d', $matches, PREG_SET_ORDER);
var_dump(count($matches));
var_dump(count($matches) >= 2 && count($matches) <= 6);
preg_match_all("#[{$pattern}]#", 'djsjKjffEf,mmddmd', $matches, PREG_SET_ORDER);
var_dump(count($matches));
var_dump(count($matches) >= 2 && count($matches) <= 6);
```
Result:
```
int(2)
bool(true)
int(4)
bool(true)
int(1)
bool(false)
```

Fixed RegEx validate database password

---

app/Http/Controllers/Auth/LoginController.php
config/auth.php

We use username(), so the cache key will be created correctly
Variables have also changed:

Fixed TooManyLoginAttempts not work correctly

---

resources/themes/pterodactyl/admin/eggs/scripts.blade.php
resources/themes/pterodactyl/admin/eggs/variables.blade.php
resources/themes/pterodactyl/admin/eggs/view.blade.php

More uniformity within the egg page.
It should be called `Install Script`, as that's what it does. It's also only one script not multiple.

More uniformity

---

Dockerfile

It's usually a better practice to use an official supported Docker image (in this case, php) so it's best optimized and supported.
Not yet tested, but it should work.

Dockerfile: Switch to php:7.2-fpm-alpine

---

app/Console/Commands/Server/BulkPowerActionCommand.php
app/Console/Commands/Server/BulkReinstallActionCommand.php

The following commands no longer need confirmation when the input is not interactive:
- server:bulk-power
- server:reinstall

Improved non-interactive command support

---

resources/views/admin/users/view.blade.php

Text boxes on the user view page were set to read-only not allowing admins to change user values

Fixed Admin user profile textboxes

---

app/Models/Server.php
database/migrations/2020_04_03_203624_add_threads_column_to_servers_table.php
resources/views/admin/eggs/variables.blade.php
resources/views/admin/eggs/view.blade.php
resources/views/admin/packs/view.blade.php
resources/views/admin/servers/view/index.blade.php

* Adds a migration for the `threads` column on the `servers` table
* Adds validation rules for the `threads` column
* Fixes an error with the `admin.nests.egg.export` route on `admin/eggs/view.blade.php`
* Fixes an error with the `admin.nests.egg.variables.edit` route on `admin/eggs/view.blade.php`
* Fixes an error with the `admin.packs.view.export` route on `admin/packs/view.blade.php`
* Displays `Not Set` for when the `threads` column is null on `admin/servers/view/index.blade.php`

Add migration and validation rules for 'threads' column, fixes other errors on nest/egg pages

---

app/Http/Controllers/Daemon/ActionController.php
app/Models/Node.php

Still returns json, as json is valid yaml anyways.
Required for pterodactyl/wings#19

re-enable auto-deploy daemon endpoint

---

resources/themes/pterodactyl/base/index.blade.php

Make sure the server-description row is as long as the server row above.

Fix server-description colspan

---

app/Services/Nodes/NodeCreationService.php

Fixed nodes not getting a UUID during creation causing a 500
Closes #1930

Fixed UUID on node creation

---

public/themes/pterodactyl/css/pterodactyl.css
resources/scripts/components/server/ServerConsole.tsx
resources/views/admin/packs/new.blade.php
resources/views/admin/users/index.blade.php

- Changed `code` color to be a little lighter, more contrast / easier to read (From #999 to #c3c3c3)
- Changed cursor for disabled / read-only to `not-allowed` instead of `text`
- Changed Link color, to be a tad lighter
- Changed well to match the dark theme. Specifically the Packs page
- Closes #1918 -> Dropdown text was grey with a grey background.
- Added Green and Yellow Text colors
- Added Text-Danger
- Added well/well-sm/well-lg to pterodactyl.css
- Added Readonly style, was a white box with grey letters. Changes to Dark grey box and white letters.
- Hovering over Start / Restart show respective colors Green / Blue

Update Admin CSS /  CSS changes

---

resources/views/admin/servers/view/index.blade.php

Changes CPU Threads show Not Set instead of n/a
Changes 0% -> Unlimited, when CPU is set to 0(unlimited)
Changes 0MB -> Unlimited, when memory is set to 0(unlimited)
Changes 0MB Swap -> Not Set
Changes -1 Swap -> Unlimited
Changes Name -> Server Name
Changes Service -> Current Egg
Mostly aesthetic / uniformity changes 
Before
After:

Update Admin Overview for server

---

app/Http/Requests/Admin/Egg/EggFormRequest.php
app/Http/Requests/Admin/Nest/StoreNestFormRequest.php
app/Models/Egg.php
app/Models/Location.php
app/Models/Nest.php
app/Models/Node.php
database/migrations/2020_04_17_203438_allow_nullable_descriptions.php
resources/views/admin/eggs/view.blade.php
resources/views/admin/nests/view.blade.php

Allows for Nest, Node, Location, and Egg description fields to be blank / nullable.
Removed "required" wording next to them as well
Closes #1922
Partially takes care of #1894

Allow description fields to be optional

---

app/Contracts/Repository/DatabaseRepositoryInterface.php
app/Http/Requests/Admin/Servers/Databases/StoreServerDatabaseRequest.php
app/Models/Database.php
app/Repositories/Eloquent/DatabaseRepository.php
app/Services/Databases/DatabaseManagementService.php
app/Services/Databases/DatabasePasswordService.php
app/Transformers/Api/Application/ServerDatabaseTransformer.php
app/Transformers/Api/Client/DatabaseTransformer.php
database/migrations/2020_04_22_055500_add_max_connections_column.php
resources/scripts/api/server/getServerDatabases.ts
resources/scripts/components/server/databases/DatabaseRow.tsx
resources/views/admin/databases/view.blade.php
resources/views/admin/servers/view/database.blade.php

Closes #1849
Allows database users to be limited to a number of concurrent connections to prevent one user from connecting hundreds of times and bottlenecking the MySQL server.

Add Max Concurrent Connections for database users

---

public/themes/pterodactyl/css/pterodactyl.css
resources/views/admin/nodes/view/allocation.blade.php
resources/views/admin/nodes/view/index.blade.php

More CSS Changes...
Server overview page now looks more..... fluid
Boxes have their correct color top colors back. When the admin side was changed to dark theme all but yellow was changed to a single color, this is reverted.
The node overview page uses blue over the gray box for total servers.
Lightened the text color on the sidebar
Removed the delete button for allocations that are assigned.
Changes Node configuration box to not hurt eyes

CSS Changes

---

database/seeds/eggs/minecraft/egg-forge-minecraft.json

Updates the forge egg to use the json api from forge to get versions instead of the old way of scraping the site and getting invalid jar files.
Also updates to validate download links.
Allows for setting a specific forge version

update forge egg

---

app/Http/Controllers/Admin/ServersController.php

Fixes #2047
Apparently I never had the value saved to the database so it was never actually used...... I probably missed that file in the original PR. 
Using beta 4 as a base and editing this file restores functionality

Save maxconnection value to DB

---

resources/scripts/components/server/ServerConsole.tsx
resources/scripts/components/server/StatGraphs.tsx

Changes server view to use bytestohuman to show 10 GB as it does on the main index.
Changed:
Removed animation duration on the graph so it doesn't look likes it glitching when a new value is pushed, also made it a little more curvier.

Change to BytesToHuman on server view for limits, to match index page. Changes to CPU/Memory Graph 

---

resources/views/admin/servers/view/index.blade.php

I guess I missed this one when I set everything to show unlimited when its 0.
Shows Unlimited disk space instead of 0 on admin about page.

Show Unlimited instead of 0MB for disk space on about page ( Admin Side )

---

resources/styles/components/forms.css
resources/styles/components/miscellaneous.css

Adds styling to the scrollbar using the WebKit in the CSS, WebKit is widely supported by most modern browsers. 
Anyone have a better idea of colors / looks for it please let me know, I was at the point of anything is better then what it currently is. 
Before(already has the syntax background change) :
After:
The last one shows the mouse hover color.
I'm open to changes... wasn't sure if it should be a color for the hover over or not?

Add scrollbar styling + change syntax background color

---

public/themes/pterodactyl/css/terminal.css

Add missing [white-space: pre-wrap] to [#terminal > .cmd]
Before
After

Fix #terminal css line formatting

---

.github/workflows/release.yml
.github/workflows/tests.yml

This adds automation for releases.
* builds assets
* creates release archive
* extracts the changelog and appends the sha256sum of the binary.
* creates a release branch and commits version
* creates a draft release
* uploads archive and checksum
The changelog is extracted from CHANGELOG.md. It takes everything between /^## <tag>/ and /^##/, aka. everything between the h2 of the current version and the next h2.
The name of the release is also extracted from the changelog from the full h2 line of the release.
If the version contains beta or alpha the release is marked as a pre-release.

add release automation

---

resources/scripts/components/dashboard/forms/DisableTwoFactorModal.tsx

Whoops! Trailing space after `<Button` on line 60.

Update DisableTwoFactorModal.tsx - Fix lint errors

---

resources/scripts/components/dashboard/ServerRow.tsx

Importing `SpinnerOverlay` is redundant since it is not used :slightly_smiling_face:

Remove unused import

---

README.md

The current link redirects to this and has an expired SSL certificate.

Fix outdated AdminLTE link in README.md

---

app/Services/Servers/ServerCreationService.php

This should fix the panel side for issue #2261. Wings will no longer crash because it will receive good data but I still think it shouldn't crash when that's not the case.
I didn't update the CHANGELOG.md since there seems to be no changelog yet for these beta version.

Fix default values not applied in server creation

---

resources/scripts/components/server/schedules/EditScheduleModal.tsx

Moves the rendering of the time boxes to proper locations to match the view on the main schedules page and to match cron syntax

Arrange cron times in proper order to match

---

resources/views/admin/nodes/view/configuration.blade.php

on the docs, you're downloading it to /usr/local/bin so it's easier like this

fix: remove ./ before wings for auto-configuration

---

config/database.php

Hi,
I'm currently in a scenario where I'm forced to connect to my Redis instance with an UNIX socket. As this is currently supported by Predis (as seen [here](https://github.com/predis/predis/wiki/Connection-Parameters)), it wasn't directly supported in Pterodacyl. So I've added it as configuration options during installation. Of course `TCP` stays the default to be backward compatible.
If there's something that I missed, I am looking forward to your comments. 😃

Add Redis UNIX socket support besides to TCP

---

resources/scripts/components/elements/Modal.tsx
resources/scripts/components/server/backups/BackupRow.tsx
resources/scripts/components/server/files/FileObjectRow.tsx
resources/scripts/components/server/files/NewDirectoryButton.tsx

Before:
After:
Also fixed long modals:
Before:
After:

Fix overflows through out the front end 

---

resources/scripts/api/swr/getServerStartup.ts

Remove console logging, as its not an error being logged i see no reason for this to be printed when the startup page is viewed.

Remove console logging
