pterodactyl/panel

README.md
Fix It just being Docs when it is also support in section
=> Update; README

app/Http/Controllers/Auth/AuthController.php, app/Http/Middleware/RedirectIfAuthenticated.php, app/Http/Routes/AuthRoutes.php, resources/lang/en/strings.php, resources/lang/en/validation.php, resources/views/auth/login.blade.php
This pull request implements the ability to use Two-factor authentication. It has been tested using Google Authenticator.
=> Implement Two-factor authentication

resources/lang/pt/auth.php, resources/lang/pt/base.php, resources/lang/pt/pagination.php, resources/lang/pt/passwords.php, resources/lang/pt/server.php, resources/lang/pt/strings.php, resources/lang/pt/validation.php
Translated all files inside resources/lang/en to brazilian portuguese. 
Now everything in one single commit.
=> Initial translation to pt_BR

resources/lang/pt/auth.php, resources/lang/pt/base.php, resources/lang/pt/pagination.php, resources/lang/pt/passwords.php, resources/lang/pt/server.php, resources/lang/pt/strings.php, resources/lang/pt/validation.php
Translated to pt_BR, now with the proper copyright things
=> Initial translation to portuguese

.env.example, config/themes.php
This adds a `APP_THEME` option to be set in the environment file. Its useful for developers, so you don't have to modify the configuration.
=> Add theme key in ENV

app/Http/Controllers/Admin/ServersController.php, app/Http/Controllers/Server/AjaxController.php, app/Http/Controllers/Server/ServerController.php, app/Models/Server.php, app/Repositories/ServerRepository.php, database/migrations/2016_08_30_212718_add_ip_alias.php, database/migrations/2016_08_30_213301_modify_ip_storage_method.php, resources/views/admin/servers/index.blade.php, resources/views/admin/servers/view.blade.php, resources/views/admin/services/options/view.blade.php, resources/views/admin/users/view.blade.php, resources/views/base/index.blade.php, resources/views/server/index.blade.php
=> Add IP Aliasing

app/Console/Commands/RunTasks.php, app/Http/Controllers/Admin/ServersController.php, app/Http/Controllers/Admin/UserController.php, app/Http/Middleware/CheckServer.php, app/Http/Routes/AdminRoutes.php, app/Models/Server.php, app/Repositories/ServerRepository.php, database/migrations/2016_09_01_193520_add_suspension_for_servers.php, database/migrations/2016_09_01_211924_remove_active_column.php, resources/views/admin/servers/index.blade.php, resources/views/admin/servers/view.blade.php, resources/views/base/index.blade.php, resources/views/errors/suspended.blade.php
=> Add server suspension

app/Console/Commands/RunTasks.php
=> Remove unnecessary brackets in RunTasks

database/seeds/SourceServiceTableSeeder.php
Although a TF2 + Insurgency game would be 10/10
=> Correct Team Fortress 2 name

resources/views/server/index.blade.php
=> Better name scheming for console

database/migrations/2016_10_23_181719_update_misnamed_bungee.php, database/seeds/MinecraftServiceTableSeeder.php
Dane can't spell.
Fixes the BungeeCord download issue for all BungeeCord Versions.
=> Fixing missing BungeeCord version

database/migrations/2016_10_23_181719_update_misnamed_bungee.php, database/seeds/MinecraftServiceTableSeeder.php
Updated the correct branch per https://github.com/Pterodactyl/Panel/pull/151
=> Correcting BungeeCord issue

app/Http/Controllers/Auth/ResetPasswordController.php, app/Http/Controllers/Base/AccountController.php, app/Models/User.php, resources/views/auth/passwords/reset.blade.php
fixes #123 
This took me way too long. 😅
=> Validate password on reset according to rules

resources/views/admin/nodes/view.blade.php, resources/views/server/index.blade.php
Nope, the current month is not a valid minute
=> Fix time axis for node and server view

app/Http/Controllers/API/ServerController.php
remove unrelated error thrown every time
=> fix api /servers/{id}/build

app/Repositories/ServerRepository.php
Useful when dealing with billing systems such as WHMCS
=> Allow API to set a custom ID for server creation.

resources/views/server/files/add.blade.php
=> fix adding current path to new file in filemanager twice

app/Http/Controllers/Admin/NodesController.php, app/Http/Controllers/Remote/RemoteController.php, app/Http/Routes/AdminRoutes.php, app/Models/Node.php, app/Models/NodeConfigurationToken.php, app/Repositories/NodeRepository.php, database/migrations/2017_01_07_154228_create_node_configuration_tokens_table.php, resources/views/admin/nodes/view.blade.php
Allows to create tokens to retrieve the configuration of specific nodes. The tokens are valid for 5 minutes and can only be used once.
On creation of a node an info message is shown about this feature.
#242 and #218
=> Configuration retrival for wings via token

resources/lang/en/base.php, resources/lang/en/navigation.php, resources/lang/en/strings.php, resources/themes/pterodactyl/base/api/index.blade.php, resources/themes/pterodactyl/layouts/master.blade.php
This is just to have an overview what I've done already.
Do not merge yet, I may do more until the redesign is completed.
=> Contribution to feature/new-theme

app/Models/Node.php, resources/themes/pterodactyl/layouts/master.blade.php, resources/views/admin/nodes/view.blade.php
Make sure the gravatar url satifies gravatars requirements on the master blade.
Also hide the admin menu when your not an admin
Among other fixes for there configuration files
=> Theme Changes

app/Repositories/ServerRepository.php
=> Location should be validated on creation of a server,

app/Http/Controllers/Auth/LoginController.php, resources/lang/en/strings.php, resources/themes/pterodactyl/auth/login.blade.php
Detects if login is an email or not, validates as email or not and uses the according user table field to authenticate.
=> allow to use the username for login as well

resources/themes/pterodactyl/admin/users/view.blade.php
Totally stolen from @ShadowKitten on discord
I've already signed the CLA :D
=> Sneaky typo fix

CHANGELOG.md, resources/lang/en/strings.php, resources/themes/pterodactyl/server/tasks/index.blade.php
I also added the last PR I made to the changelog - if that should have been there just remove it 👍
=> added a check if the task has run yet

app/Http/Middleware/HMACAuthorization.php
Fixed the time attack bug in issue #405
=> fixed the time attack bug

database/seeds/VoiceServiceTableSeeder.php
Fixing bad TS3 version and service variable.
=> Fixing TS3 service

public/themes/pterodactyl/css/pterodactyl.css
stop this http://i.imgur.com/SChxmjK.png
=> Limit login box width

resources/lang/en/base.php
Pointed out in the Discord, there was a typo in the translations.
=> Fixing spelling error.

database/seeds/SourceServiceTableSeeder.php
This will allow users to select cs:go to be installed without making a custom service.
=> Add CS:GO to Source Service Option

database/seeds/SourceServiceTableSeeder.php
This pull request will allow users to select Garry's Mod as a service option.
=> Created a GMOD Service Option

database/seeds/VoiceServiceTableSeeder.php
=> latest TS3

database/seeds/MinecraftServiceTableSeeder.php
This will allow users to select Forge as a service option.
=> Added a Forge Service Option

database/seeds/DatabaseSeeder.php, database/seeds/RustServiceTableSeeder.php
Adds my Rust service by default to the panel.
=> Add Rust Service

resources/themes/pterodactyl/admin/index.blade.php
Update to the new Donor box donation system
=> Donation link update

resources/lang/en/auth.php
Correction of 'lowecase' to 'lowercase' in the English language file.
=> Tiny spelling correction.

app/Console/Commands/InfoCommand.php, app/Console/Commands/Location/DeleteLocationCommand.php, app/Console/Commands/User/MakeUserCommand.php
=> Add missing CLI descriptions

resources/themes/pterodactyl/layouts/admin.blade.php, resources/themes/pterodactyl/layouts/master.blade.php
=> Fix issue #546 by adding swal to logouts

resources/lang/en/auth.php
=> Have the auth notice only take up one line (looks slightly nicer)

resources/themes/pterodactyl/admin/users/new.blade.php, resources/themes/pterodactyl/admin/users/view.blade.php, resources/themes/pterodactyl/layouts/master.blade.php, resources/themes/pterodactyl/server/files/edit.blade.php
Use @lang blade helper instead of {{ trans() }}
=> Use @lang blade helper instead of {{ trans() }}

app/Http/Controllers/Admin/ServersController.php, resources/lang/en/admin/server.php
The nodes create page will redirect you to the locations page if you don't have a location, the concept is the same here
=> Redirect to the nodes directory if there are nodes when trying to create a server

app/Models/Service.php
Use class string instead of magic string
=> Use class string instead of magic string

app/Repositories/Eloquent/DatabaseRepository.php, tests/Unit/Repositories/Eloquent/DatabaseRepositoryTest.php
=> Grant execute privilege

app/Http/Controllers/Admin/UserController.php
=> Redirect to users list on user deletion

public/themes/pterodactyl/js/frontend/console.js
I kept the on click in case someone needed it. 
Problem 2 on #706
=> Fix highlighting problem in the console.

CHANGELOG.md, public/themes/pterodactyl/js/frontend/console.js
Issue was data.line was null. it then would not iniate properly. simple if statement to prevent the issue and the console is super reliable now in all browsers.
Posted here as a pull request by request of Dane in the discord
=> Fix console not loading sometimes

.travis.yml, app/Http/Controllers/Admin/Nests/EggShareController.php, app/Services/Eggs/Sharing/EggImporterService.php, app/Services/Eggs/Sharing/EggUpdateImporterService.php, app/Services/Nests/NestCreationService.php, config/pterodactyl.php, database/seeds/DatabaseSeeder.php, database/seeds/EggSeeder.php, database/seeds/NestSeeder.php, database/seeds/eggs/minecraft/egg-bungeecord.json, database/seeds/eggs/minecraft/egg-forge-minecraft.json, database/seeds/eggs/minecraft/egg-spigot.json, database/seeds/eggs/minecraft/egg-sponge--sponge-vanilla.json, database/seeds/eggs/minecraft/egg-vanilla-minecraft.json, database/seeds/eggs/source-engine/egg-ark--survival-evolved.json, database/seeds/eggs/source-engine/egg-counter--strike--global-offensive.json, database/seeds/eggs/source-engine/egg-custom-source-engine-game.json, database/seeds/eggs/source-engine/egg-garrys-mod.json, database/seeds/eggs/source-engine/egg-insurgency.json, database/seeds/eggs/source-engine/egg-team-fortress2.json, database/seeds/eggs/voice-servers/egg-mumble-server.json, database/seeds/eggs/voice-servers/egg-teamspeak3-server.json, tests/Unit/Services/Eggs/Sharing/EggImporterServiceTest.php, tests/Unit/Services/Eggs/Sharing/EggUpdateImporterServiceTest.php, tests/Unit/Services/Nests/NestCreationServiceTest.php
Changes them to use the egg export files when importing to make adding new games as easy as dropping the file into the correct folder path.
=> Fix DB seeders

app/Console/Commands/Maintenance/CleanServiceBackupFilesCommand.php, app/Repositories/Eloquent/NodeRepository.php, app/Services/Schedules/Tasks/TaskCreationService.php
Replace magic numbers with constants
=> Replace magic numbers with constants

resources/themes/pterodactyl/partials/_internal/beta.blade.php
Nothing big, just noticed it *shrug*
=> Fixed how "GitHub" is written

resources/themes/pterodactyl/admin/settings.blade.php, resources/themes/pterodactyl/partials/_internal/beta.blade.php
Discord link is permanent invite to #beta-support channel.
Github link is to create a new issue on Github
=> Add links to beta

resources/lang/es/server.php
Fixed that :size was translated and it doesn't work
=> Fix maximum size translation to get it working

resources/lang/es/auth.php
Need to use "¡" in spanish at the start of an exclamative sentence.
=> Exclamative sentence

app/Repositories/Eloquent/EloquentRepository.php, app/Repositories/Repository.php
=> Fix incorrect namespace

app/Policies/APIKeyPolicy.php, app/Providers/EventServiceProvider.php, app/Providers/RouteServiceProvider.php, app/Transformers/Admin/SubuserTransformer.php, app/Transformers/User/SubuserTransformer.php
=> Remove unused imports

CHANGELOG.md, app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/Base/SecurityController.php, app/Models/User.php, app/Services/Users/ToggleTwoFactorService.php, app/Services/Users/TwoFactorSetupService.php, composer.json, composer.lock, config/app.php, config/pterodactyl.php, database/migrations/2017_11_11_161922_Add2FaLastAuthorizationTimeColumn.php, public/themes/pterodactyl/js/frontend/2fa-modal.js, resources/themes/pterodactyl/base/security.blade.php, tests/Unit/Http/Controllers/Base/SecurityControllerTest.php, tests/Unit/Jobs/Schedule/RunTaskJobTest.php, tests/Unit/Services/DaemonKeys/DaemonKeyProviderServiceTest.php, tests/Unit/Services/Users/ToggleTwoFactorServiceTest.php, tests/Unit/Services/Users/TwoFactorSetupServiceTest.php
Changes 2FA system to use updated library, double the length of the secrets, makes more options configurable, and stores the tokens in the database encrypted at rest rather than in plain text.
=> Implement changes to 2FA system

resources/themes/pterodactyl/admin/nodes/index.blade.php, resources/themes/pterodactyl/admin/packs/index.blade.php, resources/themes/pterodactyl/admin/servers/index.blade.php, resources/themes/pterodactyl/admin/users/index.blade.php, resources/themes/pterodactyl/base/index.blade.php
=> Revert "Lengthen search box"

database/seeds/eggs/source-engine/egg-garrys-mod.json
Add required package to apt install
Solution for: error=/home/container/garrysmod/bin/server_srv.so: undefined symbol: SteamInternal_ContextInit
Old Pastebin: https://pastebin.com/3s69XenF (Line 34)
=> Solution for "SteamInternal_ContextInit"

database/seeds/eggs/source-engine/egg-custom-source-engine-game.json
=> Fix a typo

resources/themes/pterodactyl/layouts/admin.blade.php, resources/themes/pterodactyl/layouts/master.blade.php
There was no dropdown and the account url was not working because of it.
=> Fixed navigation account click

.gitignore, app/Models/Permission.php, app/Services/Sftp/AuthenticateUsingPasswordService.php, resources/lang/de/server.php, resources/lang/en/server.php, resources/lang/es/server.php, resources/themes/pterodactyl/layouts/master.blade.php, tests/Unit/Services/Sftp/AuthenticateUsingPasswordServiceTest.php, tests/Unit/Services/Subusers/PermissionCreationServiceTest.php, tests/Unit/Services/Subusers/SubuserCreationServiceTest.php
- Fixed unit tests.
- Modified some permissions for more friendly naming.
- Removed subuser SFTP permissions in favor of single 'SFTP Allowed' permission.
=> Add support for allowing subusers to access SFTP.

CONTRIBUTING.md, README.md
=> Remove even more mentions of the forum

.dev/vagrant/provision.sh, .dev/vagrant/pterodactyl.conf, .gitignore
Update the php version of the development environment to fulfill the requirements of v0.7.0 and higher.
Kindest regards
Nils-Börge Margotti
=> Update php to version 7.2

.github/ISSUE_TEMPLATE.md
Using comments in markdown instead of having users delete stuff to have cleaner issues. Also a little better structure in my opinion.
=> improve issue template

README.md
=> fix a spelling error

database/seeds/eggs/voice-servers/egg-teamspeak3-server.json
Added "\n\ntouch \/mnt\/server\/.ts3server_license_accepted" and changed version number.
I've tested this changes on my installation. Works fine.
Thats my first PR. Hope thats ok so.
=> Update Teamspeak 3.1.1

resources/lang/en/base.php
`Accout API` should be `Account API`
=> Fix typo in base.php

resources/themes/pterodactyl/admin/servers/new.blade.php
=> Simple typo fix

.github/ISSUE_TEMPLATE.md
Just adding a note about issues with installing, hopefully prevents some support-only issues.
=> Update Issue Template again

resources/themes/pterodactyl/admin/eggs/new.blade.php, resources/themes/pterodactyl/admin/eggs/view.blade.php
Fixed a misspelling.  There might be more.  I'll keep an eye out.
=> Fix typo: update wether to whether

resources/themes/pterodactyl/admin/servers/view/index.blade.php
=> Don't show OOM Killer status on the Server View page

database/seeds/eggs/minecraft/egg-spigot.json
re-introducing the spigot build system into the install process.
=> Update to build spigot

database/seeds/eggs/minecraft/egg-spigot.json
=> Parkervcp patch 1

app/Contracts/Repository/NodeRepositoryInterface.php, app/Contracts/Repository/RepositoryInterface.php, app/Contracts/Repository/ServerRepositoryInterface.php, app/Http/Controllers/Admin/StatisticsController.php, app/Repositories/Eloquent/EloquentRepository.php, app/Repositories/Eloquent/NodeRepository.php, app/Repositories/Eloquent/ServerRepository.php, app/Traits/Controllers/JavascriptStatisticsInjection.php, app/Traits/Controllers/PlainJavascriptInjection.php, public/themes/pterodactyl/css/pterodactyl.css, public/themes/pterodactyl/js/admin/statistics.js, resources/themes/pterodactyl/admin/statistics.blade.php, resources/themes/pterodactyl/layouts/admin.blade.php, routes/admin.php, tests/Unit/Http/Controllers/Admin/StatisticsControllerTest.php
=> Added a statistics page to monitor the panel usage

resources/lang/de/strings.php
This change will fix a typo in a language string,
=> Fix typo in string

database/seeds/eggs/source-engine/egg-ark--survival-evolved.json
-Added Variable selection on startup commands
-In the description we have added the map available at this time.
=> Adding variable for Server Map Selection [ARK SERVER]

resources/lang/cn/command/messages.php, resources/lang/de/command/messages.php, resources/lang/en/command/messages.php, resources/lang/es/command/messages.php
=> change smtp.google.com to smtp.gmail.com

public/themes/pterodactyl/css/terminal.css
This reverts commit 955617d7ce34a49b785a87c707df6962a51ea3a7. References/fixes issue #1307.
=> Revert "Update terminal.css"

database/seeds/eggs/voice-servers/egg-teamspeak3-server.json
Use latest version to prevent issues with invalid licensekey.dat file
=> Update to latest version

Dockerfile
Required for egg uploads to the panel.
=> adding php7-info

.dev/docker/default_ssl.conf, .dev/docker/entrypoint.sh, Dockerfile, config/app.php, docker-compose.example.yml
Been meaning to push these for a bit.
=> Update to latest dockerfiles

database/seeds/eggs/voice-servers/egg-teamspeak3-server.json
Just updated to the latest TS3 Server version
=> Updated TS3 Server version

database/seeds/eggs/rust/egg-rust.json
Also I'm not sure why the default port was set to 8401.
The default port for RCON is 28016.
=> Added missing option for auto-save interval

database/seeds/eggs/minecraft/egg-forge-minecraft.json
frolvlad's oraclejdk image died and the stock openjdk image works fine for this,
=> Fix Forge Install Container

database/seeds/eggs/minecraft/egg-forge-minecraft.json
Forge broke how their html gets parsed and this is my dumb fix for it.
=> Fix for stupid forge version grabbing.

database/seeds/eggs/minecraft/egg-bungeecord.json, database/seeds/eggs/minecraft/egg-spigot.json, database/seeds/eggs/minecraft/egg-sponge--sponge-vanilla.json, database/seeds/eggs/minecraft/egg-vanilla-minecraft.json, database/seeds/eggs/terraria/egg-terraria-server--t-shock.json, database/seeds/eggs/voice-servers/egg-mumble-server.json, database/seeds/eggs/voice-servers/egg-teamspeak3-server.json
Updated alpine version used for install containers, so its only one version and not 4
=> Update to latest Alpine

database/seeds/eggs/source-engine/egg-ark--survival-evolved.json
Changes the ARK startup config to actually set the server to running.
=> Fix ARK startup config

resources/themes/pterodactyl/server/databases/index.blade.php
I guess it was left out of https://github.com/pterodactyl/panel/pull/1260
=> Add missing ∞

app/Models/Node.php
Messed up #1512 really badly and couldn't re-open it but this looks correct...
=> Allow nodes to be created on privileged ports

database/seeds/eggs/voice-servers/egg-teamspeak3-server.json
use a debian based image instead due to glibc issues
resolves #1606
=> update teamspeak egg

composer.json, composer.lock, database/seeds/eggs/source-engine/egg-insurgency.json, database/seeds/eggs/voice-servers/egg-teamspeak3-server.json
PHP 7.3 compatibility fix, insurgency egg fix, teamspeak egg update.
=> Some Fixes

README.md
=> Change guides link to new community section in the documentation

database/seeds/eggs/source-engine/egg-garrys-mod.json
=> Updated gmod egg

database/seeds/eggs/minecraft/egg-paper.json
I realized after it was accepted I left in the server query.
This is to remove it.
=> remove paper query port again

app/Http/Controllers/Admin/DatabaseController.php
Otherwise this errors out with $host not being found
=> Missing return statement

app/Services/Nests/NestDeletionService.php
Fixed "Nest has active servers error"
https://justmyrandomstuff.com/img/bkCdluU.jpg
To 
https://justmyrandomstuff.com/img/rgYkMHR.jpg
=> Fixed has servers error message

resources/themes/pterodactyl/admin/nodes/new.blade.php
Fixes https://github.com/pterodactyl/panel/issues/1731
=> Fix for new node on mobile 

resources/themes/pterodactyl/server/files/list.blade.php
Fixes the issue referenced in #1613
Recreation of pull request https://github.com/pterodactyl/panel/pull/1617 on correct branch
=> Fixes file 404 error, closes pterodactyl#1613

database/migrations/2016_10_23_193810_add_foreign_keys_servers.php
Fixes for users wanting to run MySQL v8+
=> MySQL 8 fix

database/seeds/eggs/minecraft/egg-vanilla-minecraft.json
Update the install script to work properly.
=> update vanilla minecraft script.

resources/themes/pterodactyl/server/schedules/new.blade.php
=> Fix new schedule header

resources/scripts/components/auth/LoginCheckpointContainer.tsx, resources/scripts/components/server/Console.tsx
Fixes #1812 (The sizing issue on the 2FA page after entering a username and password)
Fixes #1813 (The inability to copy text from xterm.js on the server console page)
=> Fix 2FA sizing issue, add support for copying text from xterm.js

resources/themes/pterodactyl/admin/index.blade.php
=> Update Admin Links

resources/scripts/TransitionRouter.tsx
Fixed CR Year,
Figured id do it correctly :)
=> Fixed Copyright year

app/Http/Controllers/Api/Client/AccountController.php, app/Http/Requests/Api/Client/Account/UpdatePasswordRequest.php
=> Change to new password and fix #1891

resources/views/admin/servers/new.blade.php, resources/views/admin/servers/view/build.blade.php, resources/views/admin/servers/view/index.blade.php
Fixed auto-sizing for resource management
Moved options to a more logical order
Old:![Old](https://media.discordapp.net/attachments/272117330207571969/698010821556699146/UqP0gBJ.png?width=854&height=277)
New:![New](https://justmyrandomstuff.com/img/edt1rno.gif)
=> New server formatting

resources/scripts/components/server/ServerConsole.tsx
Added Disk usage to console page, matches the same information on the overview page.
=> Add Disk display to console view

database/migrations/2020_04_03_203624_add_threads_column_to_servers_table.php
Put column after CPU, not at the end.
=> Move threads column to the

app/Services/Nodes/NodeCreationService.php
Fixes the encryption issue when creating a new node (encrypt the token, not the token_id) 🤦‍♂️ 
https://bin.ptdl.co/4cxz5/
=> Fix encryption issue when creating new nodes

docker-compose.example.yml
Adds restarting for the containers.
=> update docker-compose file

app/Notifications/AddedToServer.php
Closes #2009 
When calling `route('server.index')` it appends `/api/servers`
Not sure if this is a proper solution or not, but it fixes the issue.
@Sauronox in discord reported the issue, asked to open an issue, Has yet to open one. Will post relevant info below
https://discordapp.com/channels/122900397965705216/658550982975946762/708437731939844097
Stack Trace 
```
[2020-05-08 23:54:31] production.ERROR: LogicException: Route for [api/server/{server}] has no action. in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php:63
Stack trace:
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\RouteAction::Illuminate\Routing\{closure}('50cc6b51')
#1 …
```
=> Fix Subuser welcome email

app/Models/Node.php
No longer needed in wings config.
=> Remove timezone from config

database/seeds/eggs/voice-servers/egg-mumble-server.json
The title says it all. Updated the default version in the Mumble egg.
=> Update default value for "MUMBLE_VERSION" to latest version

resources/scripts/components/dashboard/ServerRow.tsx, resources/scripts/components/server/ServerConsole.tsx
Shows unlimited for resources if they're set to "0"
I'm sure we could also just remove the "of {limit}" part if its unlimited? Dane Advise
I'm sure there is a 100x better way of doing this? Dane, please advise.
=> Show "unlimited" not 0

resources/scripts/components/server/backups/BackupContainer.tsx
Removes Create button when feature limit is 0, also states backups cannot be created 
Adds Using x of x backups, Removes create button when the limit is reached
=> Backup page edits, Shows client x of x backups when limit > 0. Removes create button if limit is reached or limit is 0

resources/scripts/components/server/databases/DatabasesContainer.tsx
Same logic as PR #2088
Shows using x of x databases.
Once the limit is reached the create button is removed
=> Database page edits, Shows message x of x databases when limit > 0, removes create button once limit is reached.

app/Http/Middleware/Api/Client/Server/AuthenticateServerAccess.php
Fixes slight spelling issue in the AccessDeniedHttpException response.
=> Fix AuthenticateServerAccess middleware spelling issue.

resources/scripts/components/dashboard/ServerRow.tsx
"Unlimited" -> 'Unlimited'
Removed extra blank line
=> Update ServerRow.tsx - Fix yarn compile errors.

resources/views/admin/nodes/index.blade.php, resources/views/admin/servers/index.blade.php, resources/views/admin/users/index.blade.php
=> Fix table search bar not rendering properly across browsers

app/Http/Requests/Admin/Settings/BaseSettingsFormRequest.php, app/Http/ViewComposers/AssetComposer.php, app/Providers/SettingsServiceProvider.php, package.json, resources/scripts/components/App.tsx, resources/scripts/routers/AuthenticationRouter.tsx, resources/scripts/routers/DashboardRouter.tsx, resources/scripts/routers/ServerRouter.tsx, resources/scripts/state/settings.ts, resources/views/admin/settings/index.blade.php, yarn.lock
Added Google Analytics to the latest dev branch
Value is configurable within the settings page on the admin side. 
This PR replaces PR https://github.com/pterodactyl/panel/pull/1971
Closes Issue #1331
=> Add Google Analytics Support

resources/scripts/assets/css/GlobalStylesheet.ts, resources/scripts/components/server/backups/BackupContainer.tsx
Fixed backup message still using old method of "className" changed to use css={ts}
readded scrollbar styling from https://github.com/pterodactyl/panel/pull/2118
=> Re-add scroll bar style, fix missed tw conversion

resources/scripts/components/dashboard/AccountApiContainer.tsx, resources/scripts/components/dashboard/AccountOverviewContainer.tsx, resources/scripts/components/dashboard/DashboardContainer.tsx, resources/scripts/components/server/users/UsersContainer.tsx
Moves the rest of the page titles to Content Blocks
=> Move page titles to PageContentBlocks

resources/lang/en/exceptions.php
This error message isn't updated for wings 1.0 .
=> Update daemon_off_config_updated message core.json is now config.yml

resources/scripts/components/dashboard/ServerRow.tsx, resources/scripts/components/server/ServerConsole.tsx, resources/scripts/components/server/users/UserRow.tsx, resources/views/admin/servers/new.blade.php, resources/views/admin/servers/view/details.blade.php
Fixed Server row overflow for servers name and description
Fixed Sub-user overflow for users with oddly long emails...
Fixed Server new overflow on console view.
See Attached images. Issues were posted in #2365
=> Fix overflows through out the front end

resources/scripts/components/server/ServerConsole.tsx, resources/scripts/components/server/StatGraphs.tsx
Fixed console size on lg
Fixed the power button panel on lg
Fixed graphs that were huge in size
Partial fixed apply to #2365. Need fix console text overflow (I have no idea how to do this)
=> Partial fix for mobile responsiveness

resources/views/admin/servers/new.blade.php, resources/views/admin/servers/view/build.blade.php, resources/views/admin/servers/view/index.blade.php
=> Rename CPU Threads for CPU Pinning

resources/views/admin/settings/advanced.blade.php
=> Remove unused settings from admin side
